# -*- coding: utf-8 -*-
"""NLP_ABSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v5IW7MITHOSFhuy9NfgTDkOncvm-gFLP

##Phase 1 : ( SemEval dataset + predefined aspects + VADER for sentiment )
"""

import os
import pandas as pd
import numpy as np
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.metrics import accuracy_score, f1_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('vader_lexicon')

!kaggle datasets download charitarth/semeval-2014-task-4-aspectbasedsentimentanalysis

!unzip semeval-2014-task-4-aspectbasedsentimentanalysis.zip

import xml.etree.ElementTree as ET
import pandas as pd

def parse_xml(file_path, domain):
    tree = ET.parse(file_path)
    root = tree.getroot()

    data = []

    for sentence in root.findall('sentence'):
        text = sentence.find('text').text

        aspect_terms = sentence.find('aspectTerms')

        if aspect_terms is not None:
            for aspect in aspect_terms.findall('aspectTerm'):
                term = aspect.get('term')
                polarity = aspect.get('polarity')

                data.append({
                    'sentence': text,
                    'aspect': term,
                    'sentiment': polarity,
                    'domain': domain
                })

    return pd.DataFrame(data)

# Parse both domains
laptop_df = parse_xml("Laptop_Train_v2.xml", "laptop")
restaurant_df = parse_xml("Restaurants_Train_v2.xml", "restaurant")

# Combine
df = pd.concat([laptop_df, restaurant_df], ignore_index=True)

# Save CSV
df.to_csv("semeval_absa.csv", index=False)

print("CSV created successfully!")
print(df.head())

from google.colab import drive
drive.mount('/content/drive')

df.to_csv("/content/drive/MyDrive/ABSA/semeval_absa.csv", index=False)

# ==============================
# STEP 1: LOAD DATASET (SemEval Format)
# ==============================

DATA_PATH = "/content/drive/MyDrive/semeval_absa.csv"
df = pd.read_csv(DATA_PATH)

print("Sample Data:")
print(df.head())
print("\n")
print(df.shape)

df = df[df['sentiment'] != 'conflict']

# ==============================
# STEP 2: DATA CLEANING
# ==============================

def clean_text(text):
    text = str(text).lower()
    text = text.replace("\n", " ")
    return text


df['clean_sentence'] = df['sentence'].apply(clean_text)

# ==============================
# STEP 3: FILTER DOMAIN (Laptop/Restaurant)
# ==============================

# Assuming dataset has domain column (if not, manually split datasets)

if 'domain' in df.columns:
    df = df[df['domain'].isin(['laptop', 'restaurant'])]

# ==============================
# STEP 4: PREDEFINED ASPECTS
# ==============================

PREDEFINED_ASPECTS = [
    'battery', 'screen', 'price', 'performance', 'design',
    'food', 'service', 'ambience'
]

# Function to map aspect to predefined category

def map_aspect(aspect):
    for a in PREDEFINED_ASPECTS:
        if a in aspect.lower():
            return a
    return 'other'


df['mapped_aspect'] = df['aspect'].apply(map_aspect)

# ==============================
# STEP 5: SENTIMENT USING VADER
# ==============================

sia = SentimentIntensityAnalyzer()

def get_sentiment(text):
    score = sia.polarity_scores(text)['compound']
    if score >= 0.05:
        return 'positive'
    elif score <= -0.05:
        return 'negative'
    else:
        return 'neutral'


df['predicted_sentiment'] = df['clean_sentence'].apply(get_sentiment)

# ==============================
# STEP 6: AGGREGATION
# ==============================

result = {}

for aspect in df['mapped_aspect'].unique():
    subset = df[df['mapped_aspect'] == aspect]
    result[aspect] = {
        'positive': sum(subset['predicted_sentiment'] == 'positive'),
        'negative': sum(subset['predicted_sentiment'] == 'negative'),
        'neutral': sum(subset['predicted_sentiment'] == 'neutral')
    }

print("\nAggregated Results:")
print(result)

# Convert to DataFrame for plotting
plot_df = pd.DataFrame(result).T
plot_df = plot_df.fillna(0)

# ==============================
# STEP 7: VISUALIZATION
# ==============================

plot_df.plot(kind='bar', figsize=(10,6))
plt.title("Aspect-wise Sentiment Distribution")
plt.xlabel("Aspect")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()



# ==============================
# STEP 8: EVALUATION
# ==============================

# Ensure ground truth sentiment labels exist
if 'sentiment' in df.columns:
    # Ensure predicted_sentiment column exists before proceeding
    if 'predicted_sentiment' in df.columns:
        y_true = df['sentiment']
        y_pred = df['predicted_sentiment']

        acc = accuracy_score(y_true, y_pred)
        f1 = f1_score(y_true, y_pred, average='weighted')

        print("\nEvaluation Metrics:")
        print(f"Accuracy: {acc:.4f}")
        print(f"F1 Score: {f1:.4f}")
        print("\nClassification Report:")
        print(classification_report(y_true, y_pred))
    else:
        print("Error: 'predicted_sentiment' column not found in DataFrame. Please ensure the sentiment prediction step (Step 5) has been executed successfully.")
else:
    print("Error: 'sentiment' column (ground truth) not found in DataFrame. Cannot perform evaluation.")

SAVE_PATH = "/content/drive/MyDrive/ABSA/absa_results.csv"
df.to_csv(SAVE_PATH, index=False)

print(f"Results saved to {SAVE_PATH}")

"""##Phase 2: ( Amazon Electronics Dataset + Predefined aspects + BERT )"""

!kaggle datasets download -d datafiniti/consumer-reviews-of-amazon-products

!unzip consumer-reviews-of-amazon-products.zip

import pandas as pd

df = pd.read_csv("1429_1.csv")  # filename may vary

print(df.columns)
df.head()

df = df[['name', 'reviews.text', 'reviews.rating']]

df.columns = ['product', 'review', 'rating']

df.dropna(inplace=True)

df.to_csv("/content/drive/MyDrive/ABSA/amazon_reviews_clean.csv", index=False)

!pip install transformers torch seaborn matplotlib

df = pd.read_csv("/content/drive/MyDrive/ABSA/amazon_reviews_clean.csv")

selected_product = df['product'].value_counts().idxmax()

product_df = df[df['product'] == selected_product].copy()

print("Selected product:", selected_product)

print("Total rows:", len(df))
print("Filtered rows:", len(product_df))
print("Unique products in filtered data:", product_df['product'].unique())

ASPECTS = ['battery', 'screen', 'camera', 'performance', 'price', 'design']

ASPECT_KEYWORDS = {
    'battery': ['battery', 'charging', 'battery life'],
    'screen': ['screen', 'display'],
    'camera': ['camera', 'photo', 'picture'],
    'performance': ['performance', 'speed', 'lag'],
    'price': ['price', 'cost', 'expensive'],
    'design': ['design', 'build', 'look']
}

def extract_aspects(review):
    review_lower = review.lower()
    found = []

    for aspect, keywords in ASPECT_KEYWORDS.items():
        if any(word in review_lower for word in keywords):
            found.append(aspect)

    return found

product_df['aspects'] = product_df['review'].apply(extract_aspects)

# Remove rows with no aspects
product_df = product_df[product_df['aspects'].map(len) > 0]

# Then explode
product_df = product_df.explode('aspects')

from transformers import pipeline

sentiment_model = pipeline("sentiment-analysis")

def get_sentiment(text):
    result = sentiment_model(text[:512])[0]  # truncate for safety

    if result['label'] == 'POSITIVE':
        return 'positive'
    else:
        return 'negative'

product_df['predicted_sentiment'] = product_df['review'].apply(get_sentiment)

import matplotlib.pyplot as plt
import pandas as pd

# Aggregate sentiment counts by aspect
plot_df = product_df.groupby('aspects')['predicted_sentiment'].value_counts().unstack(fill_value=0)

plot_df.plot(kind='bar', figsize=(10,6))

plt.title(f"Aspect-wise Sentiment Distribution for {selected_product}")
plt.xlabel("Aspect")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

import matplotlib.pyplot as plt

# Get unique aspects
unique_aspects = product_df['aspects'].unique()

# Create a figure with subplots for each pie chart
num_aspects = len(unique_aspects)
# Adjust layout based on the number of aspects for better visualization
num_cols = 3  # You can change this number based on preference
num_rows = (num_aspects + num_cols - 1) // num_cols # Calculate rows needed

fig, axes = plt.subplots(num_rows, num_cols, figsize=(num_cols * 5, num_rows * 4))
axes = axes.flatten() # Flatten the array of axes for easy iteration

for i, aspect in enumerate(unique_aspects):
    # Filter data for the current aspect
    aspect_data = product_df[product_df['aspects'] == aspect]

    # Get sentiment counts for the current aspect
    sentiment_counts = aspect_data['predicted_sentiment'].value_counts()

    # Plot pie chart
    if not sentiment_counts.empty:
        wedges, texts, autotexts = axes[i].pie(sentiment_counts, labels=sentiment_counts.index, autopct='%1.1f%%', startangle=90, colors=['#66b3ff', '#ff9999'])
        axes[i].set_title(f'{aspect.capitalize()} ')
        axes[i].axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    else:
        axes[i].text(0.5, 0.5, 'No data', horizontalalignment='center', verticalalignment='center', transform=axes[i].transAxes)
        axes[i].set_title(f'{aspect.capitalize()} ')

# Hide any unused subplots
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.suptitle(f'Sentiment Distribution by Aspect for {selected_product}', y=1.02, fontsize=16) # Overall title
plt.tight_layout(rect=[0, 0, 1, 0.98]) # Adjust layout to prevent overlap
plt.show()

def rating_to_sentiment(rating):
    return 'positive' if rating >= 4 else 'negative'

product_df['true_sentiment'] = product_df['rating'].apply(rating_to_sentiment)

from sklearn.metrics import accuracy_score, f1_score

acc = accuracy_score(product_df['true_sentiment'], product_df['predicted_sentiment'])
f1 = f1_score(product_df['true_sentiment'], product_df['predicted_sentiment'], average='weighted')

print("Accuracy:", acc)
print("F1 Score:", f1)



"""### Save and Load BERT Model to Google Drive"""

save_path = "/content/drive/MyDrive/ABSA/bert_sentiment_model"

# Save model + tokenizer
sentiment_model.model.save_pretrained(save_path)
sentiment_model.tokenizer.save_pretrained(save_path)

print("Model saved successfully!")

"""### Load BERT Model from Google Drive"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

load_path = "/content/drive/MyDrive/ABSA/bert_sentiment_model"

# Load tokenizer + model
tokenizer = AutoTokenizer.from_pretrained(load_path)
model = AutoModelForSequenceClassification.from_pretrained(load_path)

# Recreate pipeline
sentiment_model = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

print("Model loaded successfully!")

